fname=input("What is your first name?: ")
sname=input("What is your second name?: ")
location=input("What is the name of the place you are in?: ")
age=input("How are old are you?: ")
print("Hello", fname, sname+"! You are", age, "years old and are in", location+".")
exit()